apiVersion: apps/v1
kind: Deployment
metadata:
  name: webook-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webook
  template:
    metadata:
      labels:
        app: webook
    spec:
      containers:
        - name: webook
          image: registry.cn-hangzhou.aliyuncs.com/webook/webook:v1
          ports:
            - containerPort: 8080